import LegalShell from "@/components/legal/LegalShell";
import SetHeaderTitle from "@/components/SetHeaderTitle";

export const metadata = {
  title: "Terms of Service — FEELRE",
  description: "Terms for using FEELRE.",
};

export default function TermsPage() {
  return (
    <>
      <SetHeaderTitle title="Terms of Service" />
      <LegalShell updatedAt="October 2025">
        <h2>FEELRE – Terms of Service</h2>

        <p><strong>Welcome to FEELRE.</strong> By using our website or app, you agree to these terms.</p>
        
        <h3>1. Service Description</h3>
        <ul>
          <li>FEELRE is an AI-powered shopping assistant that helps users find gifts and products based on their preferences and emotions.</li>
          <li>FEELRE provides product suggestions through affiliate programs.</li>
          <li>We are not the seller of any listed items.</li>
        </ul>
        
        <h3>2. Use of the Service</h3>
        <p>
          You agree to use FEELRE responsibly. You must not upload or share harmful, illegal, or misleading content.
        </p>
        
        <h3>3. Data Usage</h3>
        <p>
          We may collect minimal user information (such as name, email, and language) to improve your experience.
        </p>
      
        <h3>4. Accuracy of Results</h3>
        <p>
          FEELRE suggestions are generated by AI and external APIs (e.g., Amazon). We do not guarantee product availability, prices, or accuracy.
        </p>
        
        <h3>5. Limitation of Liability</h3>
        <p>
          FEELRE is not responsible for any losses caused by third-party links or product purchases.
        </p>
       
        <h3>6. Termination</h3>
        <p>
          We may suspend or delete accounts that violate these terms.
        </p>
        <h3>7. Contact</h3>
        <p>
          For any questions: <a href="mailto:hello@feerly.com">hello@feerly.com</a>
        </p>
      </LegalShell>
    </>
  );
}
